version: "3.7"

services:
  tool-send-requests:
    container_name: tool-send-requests
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env
    restart: always
